name: Docker Image CI/CD

on:
  push:
  pull_request:
  workflow_dispatch: {}

jobs:
  node-ci:
    name: Node CI (npm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json','**/package.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies (npm)
        run: npm install

      - name: Build (if present)
        run: npm run build --if-present

      - name: Run tests (if present)
        run: npm test || echo "No tests to run"


  docker-build-push-deploy:
    name: Build Docker → Push ACR → Deploy WebApp
    runs-on: ubuntu-latest
    needs: node-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ===============================
      # LOGIN ACR
      # ===============================
      - name: Docker login ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_NAME_JOHAMANRIQUE10 }}
          password: ${{ secrets.ACR_PASSWORD_JOHAMANRIQUE10 }}

      # ===============================
      # BUILD & PUSH DOCKER IMAGE
      # ===============================
      - name: Build and Push image to ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/devopsframework:latest

      # ===============================
      # DEPLOY TO AZURE WEB APP
      # ===============================
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/devopsframework:latest
