name: Docker Image CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: 'Repository of the image'
        required: true
        default: 'devopsframework'
      IMAGE_TAG:
        description: 'Tag of the image'
        required: true
        default: 'latest'
      AZURE_WEBAPP_NAME:
        description: 'Nombre del App Service en Azure'
        required: true
      PORT:
        description: 'Puerto de la aplicaci√≥n'
        required: true
        default: '443'

env:
  IMAGE_URL: framedev2.azurecr.io/${{ github.event.inputs.IMAGE_REPOSITORY }}:${{ github.event.inputs.IMAGE_TAG }}

jobs:
  node-ci:
    name: Node CI (npm)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json','**/package.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build (if present)
        run: npm run build --if-present

      - name: Run tests (if present)
        run: npm test || echo "No tests to run"


  build-and-push-image:
    name: Build and Push to ACR
    runs-on: ubuntu-latest
    needs: node-ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: framedev2.azurecr.io
          username: ${{ secrets.ACR_NAME_JOHAMANRIQUE10 }}
          password: ${{ secrets.ACR_PASSWORD_JOHAMANRIQUE10 }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}


  deploy:
    name: Deploy remote container to Azure
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_URL }}


  test-deploy:
    name: Test deployed service
    runs-on: ubuntu-latest
    needs: [build-and-push-image, deploy]

    steps:
      - name: Checkout session.hurl
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            session.hurl
          sparse-checkout-cone-mode: false

      - name: Setup hurl
        uses: gacts/install-hurl@v1

      - name: Test API
        run: |
          hurl --variable host=https://${{ github.event.inputs.AZURE_WEBAPP_NAME }}.azurewebsites.net:${{ github.event.inputs.PORT }} \
               --connect-timeout 20s \
               --error-format long \
               --verbose \
               --test session.hurl
